spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/owner_db
    username: postgres  
    password: "Nut@n803212"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect  # Explicitly set dialect
      "[hibernate.format_sql]": true